- name: Update apt cache
  apt:
    update_cache: yes

- name: Install packages (Debian)
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_to_install }}"
  when: packages_to_install|length > 0

- name: Remove packages (Debian)
  apt:
    name: "{{ item }}"
    state: absent
  with_items: "{{ packages_to_remove }}"
  when: packages_to_remove|length > 0

- name: Update all packages if specified (Debian)
  apt:
    upgrade: yes
  when: perform_update == true