- name: Install packages (RedHat)
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_to_install }}"
  when: packages_to_install|length > 0

- name: Remove packages (RedHat)
  yum:
    name: "{{ item }}"
    state: absent
  with_items: "{{ packages_to_remove }}"
  when: packages_to_remove|length > 0

- name: Update packages if specified (RedHat)
  yum:
    name: "*"
    state: latest
  when: perform_update == true